# PC -> HDMI IN do UD851B -> TV. Atraso aplicado pelo Equalizer APO.
audio-device=wasapi/{0aa75ae7-e336-4cd9-8281-33745f0863e0}
audio-exclusive=no
audio-fallback-to-null=no
audio-channels=5.1,5.1(side),stereo,mono
audio-spdif=
ad-lavc-downmix=no
af=
volume=100
volume-max=100
speed=1
