# Todos os players enviam PCM ao cabo virtual; o relay global codifica/delaya.
audio-device=wasapi/{1480f3d6-872e-45ff-a839-c8b330d0127e}
audio-exclusive=no
audio-fallback-to-null=no
audio-channels=5.1,5.1(side),stereo,mono
audio-spdif=
ad-lavc-downmix=no
af=
volume=100
volume-max=100
