# PCM 5.1 no stdin em WAV continuo; pacotes pequenos, nao rawaudio de 125 ms.
# Correcao relativa: FL/FR 76.792 ms; CEN 5.792 ms; SL/SR 71 ms; LFE 0 ms.
audio-device=wasapi/{00000000-0000-0000-0000-000000000000}
audio-exclusive=yes
audio-fallback-to-null=no
audio-channels=5.1
audio-spdif=
ad-lavc-downmix=no
af=lavfi=[asetrate=48002,aresample=48000:filter_size=64:phase_shift=10:cutoff=0.97,asplit@cenBass=2[cbmain][cbsub];[cbsub]pan=mono|c0=c2,lowpass@cenBassA=f=120.0:p=2,lowpass@cenBassB=f=120.0:p=2,pan=5.1|c0=0*c0|c1=0*c0|c2=0*c0|c3=1*c0|c4=0*c0|c5=0*c0[cblfe];[cbmain][cblfe]amix@cenBass=inputs=2:normalize=0:dropout_transition=0,asplit@surBass=2[sbmain][sbsur];[sbmain]pan=5.1|c0=c0|c1=c1|c2=c2|c3=c3|c4=0*c4|c5=0*c5[sbkeep];[sbsur]pan=stereo|c0=c4|c1=c5,acrossover=split=90.0:order=4th:precision=double[sblo][sbhi];[sblo]pan=5.1|c0=0*c0|c1=0*c1|c2=0*c0|c3=1*c0+1*c1|c4=0*c0|c5=0*c1[sblfe];[sbhi]pan=5.1|c0=0*c0|c1=0*c1|c2=0*c0|c3=0*c0|c4=c0|c5=c1[sbtop];[sbkeep][sblfe][sbtop]amix@surBass=inputs=3:normalize=0:dropout_transition=0,adelay=3686S|3686S|278S|0S|3408S|3408S,pan@lfeheadroom=5.1|c0=c0|c1=c1|c2=c2|c3=0.333333333333*c3|c4=c4|c5=c5,equalizer@lfe20=f=20.0:t=q:w=2.0:g=6.0:c=LFE:b=0:r=f64,equalizer@lfe25=f=25.0:t=q:w=2.0:g=6.0:c=LFE:b=0:r=f64,equalizer@lfe30=f=30.0:t=q:w=2.0:g=6.0:c=LFE:b=0:r=f64,equalizer@lfe40=f=40.0:t=q:w=2.0:g=5.5:c=LFE:b=0:r=f64,equalizer@lfe50=f=50.0:t=q:w=2.0:g=1.5:c=LFE:b=0:r=f64,equalizer@lfe60=f=60.0:t=q:w=2.0:g=-4.0:c=LFE:b=0:r=f64,equalizer@lfe80=f=80.0:t=q:w=2.0:g=1.0:c=LFE:b=0:r=f64,equalizer@lfe100=f=100.0:t=q:w=2.0:g=1.0:c=LFE:b=0:r=f64,equalizer@lfe120=f=120.0:t=q:w=2.0:g=-2.5:c=LFE:b=0:r=f64,volume@master51=volume=0.04:precision=double],lavcac3enc=tospdif=yes:bitrate=640:minch=6
audio-buffer=0.032
volume=100
volume-max=100
speed=1
cache=no
demuxer=lavf
demuxer-lavf-format=wav
demuxer-lavf-probe-info=no
demuxer-lavf-o=ignore_length=1,max_size=11520
demuxer-lavf-buffersize=4096
stream-buffer-size=8192
demuxer-readahead-secs=0
demuxer-max-bytes=64KiB
input-ipc-server=\\.\pipe\SistemaArtesanalAudio51
terminal=no
osc=no
input-media-keys=no
media-controls=no
input-default-bindings=no
load-scripts=no
priority=abovenormal
